# Generated by Django 4.1.3 on 2022-11-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('message', models.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Foydalanuvchilar Loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='-----', max_length=100, null=True)),
                ('tg_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=300)),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('post_type', models.SmallIntegerField(choices=[(1, 'image'), (2, 'video'), (3, 'audio'), (4, 'text')], default=2)),
                ('channel', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_users', to='tg.users')),
            ],
            options={
                'verbose_name_plural': 'Post',
                'ordering': ['-created_at'],
            },
        ),
    ]
