# Generated by Django 4.1.3 on 2022-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_post',
            field=models.BooleanField(default=False),
        ),
    ]
